### ISSUE TITLE
Database Schema?

### ISSUE THREAD

**Issue by amadden80** [RadWells/RESTurant_app#1]
I don't see any database schema information.  What is in your database?  

I could find this information by looking at ActiveRecord migration files or some `.sql` files.
I want some way of learning what is happening in your database.

**Comment by RadWells** [comment]
Well that is because I did not use migrations to create and full my database. It is one of the things that need to be put into place in the next round of development for the app.

As I said on the survey there are a number of technologies that I intend to implement. I apologize.

**Comment by amadden80** [comment]
No apologizes!  I didn't mean "Where is the active record".

Regardless of what technologies is used, I just want to see how the
database is created.
For the immediate future, maybe make a .sql file with the statements needed
like
"CREATE TABLE foods"  etc.
